version: '2'
services:
    smartinvestplus-app:
        image: smartinvestplus
        external_links:
            - smartinvestplus-mysql:mysql
            - smartinvestplus-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/smartinvestplus?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    smartinvestplus-mysql:
        extends:
            file: mysql.yml
            service: smartinvestplus-mysql
    smartinvestplus-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: smartinvestplus-elasticsearch
