version: '2'
services:
    smartinvestplus-elasticsearch:
        container_name: smartinvestplus-elasticsearch
        image: elasticsearch:1.7.5
        # volumes:
        #     - ~/volumes/jhipster/smartinvestplus/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
